### ISSUE TITLE
tag per sheet

### ISSUE THREAD

**Issue by namimap** [alexandermendes/marc2excel#2]
Could the following feature request be evaluated and implemented, if it sounds useful?

Would not it be better, to have each tag in a separate sheet?

For example tag 600 would have its own sheet, 245 on another standalone sheet, etc, or perhaps the option to have each tag into separate excel files?

**Comment by alexandermendes** [comment]
Outputting each tag to a separate file sounds problematic as you could end up generating hundreds of different files (and it would be too difficult to transform them back again).

But, I could see about adding an option to output each tag to a separate sheet.

**Comment by alexandermendes** [comment]
Sorry, I think it's actually not worth implementing this now as it just complicates things. Again, you could end up with a spreadsheet with 200 tabs. If you want to place each column in separate tabs you could probably put together a simple Excel macro.
